name: contour-u
channels:
  - comet_ml
  - conda-forge
  - pytorch
  - simpleitk
  - defaults
dependencies:
  - python
  - pip
  - setuptools
  - cudatoolkit=10.1
  - pip:
    - -r requirements.txt
    - -r dev.txt
    - -r ../vital/requirements/requirements.txt
    - -e ../vital[dev]
    - -e ../.
